name: 'Validate skip QA label'

on:
  pull_request_target:

jobs:
  validate-skip-qa:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get files changed
        id: changed_files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c
      
      - name: Format file list for comment
        id: format_files
        run: |
            formatted_list=$(echo "${{ steps.changed_files.outputs.all_changed_files }}" | tr ' ' '\n')
            echo "------>>>>formatted_list ==>> " $formatted_list
            echo "file_list<<EOF" >> $GITHUB_OUTPUT
            echo "$formatted_list" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT