name: Retry

on:
  workflow_run:
    types:
      - completed
    workflows:
      - CI

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Attempt: ${{ github.event.workflow_run.run_attempt }}"
          echo "Run ID: ${{ github.event.workflow_run.id }}"
          echo "--- Full Event ---"
          echo '${{ toJson(github.event.workflow_run) }}'
  
  retry:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt == 1
    steps:
      - run: |
          gh run rerun ${{ github.event.workflow_run.id }} --repo echowhoami/retry-test --failed || exit 0
